---
- name: "Copy kubernetes.list"
  ansible.builtin.template:
    src: 'kubernetes.repo.astralinux1.j2'
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644

- name: Create keyrings directory
  file: path=/usr/share/keyrings state=directory mode=0755

# Download kubernetes-archive-keyring.gpg with proxy and without proxy
- name: "Download kubernetes-archive-keyring.gpg"
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp/kubernetes-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644
  when: not ((proxy_server | length > 0) and (proxy_port | length > 0))

- name: "Download kubernetes-archive-keyring.gpg with proxy"
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644
  environment:
    http_proxy: "http://{{ proxy_server }}:{{ proxy_port }}"
    https_proxy: "http://{{ proxy_server }}:{{ proxy_port }}"
  when: (proxy_server | length > 0) and (proxy_port | length > 0)

- name: "Add key to keyrings"
  shell: "cat /tmp/kubernetes-archive-keyring.gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg"

#- name: Run the equivalent of "apt-get update" as a separate step
#  ansible.builtin.apt:
#    update_cache: yes

- name: "apt update"
  command: "apt update"
  register: output

- name: Output apt update
  debug:
    msg: "{{ output.stdout.split('\n') }}"

- name: Install kubernetes packages
  apt:
    name: [kubelet,kubeadm,kubectl]
    update_cache: yes
  when: not (k8s_packages_version | length > 0)

- name: Install kubernetes packages
  apt:
    name: ["kubelet={{ k8s_packages_version }}","kubeadm={{ k8s_packages_version }}","kubectl={{ k8s_packages_version }}"]
    update_cache: yes
  when: (k8s_packages_version | length > 0)

- name: Hold packages
  shell: "apt-mark hold kubelet kubeadm kubectl"

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
