---
#- name: Run the equivalent of "apt-get update" as a separate step
#  ansible.builtin.apt:
#    update_cache: yes

- name: "apt update"
  command: "apt update"
  register: output

- name: Output apt update
  debug:
    msg: "{{ output.stdout.split('\n') }}"

- name: Install kubernetes packages from Astra Linux repo
  apt:
    name: [kubernetes-master, kubernetes-admin, kubernetes-client, kubernetes-node]
    update_cache: yes
  when: not (k8s_packages_version | length > 0)

- name: Install kubernetes packages from Astra Linux repo specific version
  apt:
    name: ["kubernetes-master={{ k8s_packages_version }}", "kubernetes-admin={{ k8s_packages_version }}", "kubernetes-client={{ k8s_packages_version }}", "kubernetes-node={{ k8s_packages_version }}"]
    update_cache: yes
  when: (k8s_packages_version | length > 0)

- name: Hold packages
  shell: "apt-mark hold kubernetes-master kubernetes-admin kubernetes-client kubernetes-node"

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
