---
- name: PRE tasks 2
  include_tasks: "pre_tasks.yml"
  when: pre_tasks2
  tags: pre_tasks2

- name: Configure firewall 2
  include_tasks: "{{ item }}"
  with_first_found:
    - "configure_firewall2_{{ os_distrib_version }}.yml"
    - "configure_firewall2_{{ os_family_version }}.yml"
    - "configure_firewall2_{{ os_distrib }}.yml"
    - "configure_firewall2_{{ os_family }}.yml"
  when: firewall and (not remove_firewall)
  tags: firewall

- name: Disable swap
  import_tasks: disable_swap.yml
  tags: dis_swap

- name: Load required kernel modules and sysctl configs
  import_tasks: load_kernel_modules_sysctl.yml
  tags: kernel_mod

- name: Configure /etc/hosts file on each node
  import_tasks: configure_etc_hosts_file.yml
  when: etc_hosts
  tags: etc_hosts

- name: Configure container runtime (CRI)
  include_tasks: "{{ item }}"
  args:
    apply:
      tags:
        - cri
  with_first_found:
    - "setup_{{ container_runtime }}_{{ os_distrib_version }}.yml"
    - "setup_{{ container_runtime }}_{{ os_family_version }}.yml"
    - "setup_{{ container_runtime }}_{{ os_distrib }}.yml"
    - "setup_{{ container_runtime }}_{{ os_family }}.yml"
  tags: cri
  when: not only_prepare_os_for_k8s

- name: Install k8s packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "install_k8s_packages_{{ os_distrib_version }}.yml"
    - "install_k8s_packages_{{ os_family_version }}.yml"
    - "k8s_repo_{{ os_distrib }}.yml"
    - "k8s_repo_{{ os_family }}.yml"
  tags: k8s_pack
  when: not only_prepare_os_for_k8s

- name: Download k8s docker images 
  command: "kubeadm config images pull"
  register: output
  tags: ddi
  when: (not only_prepare_os_for_k8s) and (inventory_hostname in groups['kube_masters'])

- name: Output download k8s docker images
  debug:
    msg: "{{ output.stdout.split('\n') }}"
  when: (not only_prepare_os_for_k8s) and (inventory_hostname in groups['kube_masters'])

- name: POST tasks 2
  include_tasks: "post_tasks.yml"
  when: (not only_prepare_os_for_k8s) and post_tasks2
  tags: post_tasks2
