---
- name: Check if cgroup memory and swapaccount in kernel
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "cgroup_enable=memory swapaccount=1"
  register: cgroup_status
  ignore_errors: true

- name: Enable cgroup memory and swapaccount
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 cgroup_enable=memory swapaccount=1"' backrefs=yes
  when: cgroup_status.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: cgroup_status.stdout == "0"
